#!/usr/bin/env python3
"""Regenerate `src/word_table.rs` from the running interpreter's `re \\w`.

Python's `re \\w` (str) is `str.isalnum() or '_'`, which no Unicode property
expression in the `regex` crate reproduces exactly (1,710 BMP code points
differ: `No` numerics like ² on one side, `M` marks and join controls on the
other — swept in Phase 1). So the table is baked: all 1,114,112 code points,
as inclusive ranges, binary-searched at runtime.

Regenerate only when the MSRV Python's Unicode data changes, then re-run the
`char_classes_match_cpython` differential. Any delta means the patterns that
consume `is_word_char` need re-verification, not silent acceptance.
"""

from __future__ import annotations

import re
from pathlib import Path

HEADER = """\
//! Python `re \\w` (str) membership, baked from CPython.
//!
//! Generated by `etc/gen_word_table.py` — do not edit by hand.
"""


def word_ranges() -> list[tuple[int, int]]:
    word = re.compile(r"\w").match
    out: list[tuple[int, int]] = []
    start = prev = None
    for i in range(0x110000):
        if word(chr(i)) is not None:
            if start is None:
                start = prev = i
            elif i == prev + 1:
                prev = i
            else:
                out.append((start, prev))
                start = prev = i
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out


def main() -> None:
    ranges = word_ranges()
    lines = [HEADER]
    lines.append("/// Inclusive [first, last] code-point ranges where Python re \\w matches.")
    lines.append("pub const WORD_RANGES: &[(u32, u32)] = &[")
    lines.extend(f"    (0x{a:04X}, 0x{b:04X})," for a, b in ranges)
    lines.append("];")
    lines.append("")
    lines.append("/// Python `re \\w` (str) membership for one character.")
    lines.append("pub fn is_word_char(c: char) -> bool {")
    lines.append("    let cp = c as u32;")
    lines.append("    WORD_RANGES")
    lines.append("        .binary_search_by(|&(lo, hi)| {")
    lines.append("            if cp < lo {")
    lines.append("                std::cmp::Ordering::Greater")
    lines.append("            } else if cp > hi {")
    lines.append("                std::cmp::Ordering::Less")
    lines.append("            } else {")
    lines.append("                std::cmp::Ordering::Equal")
    lines.append("            }")
    lines.append("        })")
    lines.append("        .is_ok()")
    lines.append("}")
    Path("src/word_table.rs").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(ranges)} ranges")


if __name__ == "__main__":
    main()
