#!/usr/bin/env python3
"""Regenerate `src/case_tables.rs` from the running interpreter's verdicts.

Run under the repo uv Python (CPython 3.13): a newer interpreter's Unicode
data silently changes the tables.

`bible_layout._confident_heading` reads `str.isupper()`/`str.islower()` off
block initials. For a single character those are *almost* General_Category
Lu/Ll — except non-`Lu` letters like U+2160 ROMAN NUMERAL ONE, which CPython
still counts as upper. So the verdicts are baked: all 1,114,112 code points
(minus surrogates, unrepresentable as Rust `char`), as inclusive ranges,
binary-searched at runtime.

Regenerate only when the MSRV Python's Unicode data changes, then re-run the
case sweep in the Phase 3 differential. Any delta means `bible_layout`'s
heading rule needs re-verification, not silent acceptance.
"""

from __future__ import annotations

from pathlib import Path

HEADER = """\
//! Single-character `str.isupper()` / `str.islower()` verdicts, baked from CPython.
//!
//! Generated by `etc/gen_case_tables.py` — do not edit by hand.
"""


def verdict_ranges(pred) -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []
    start = prev = None
    for i in range(0x110000):
        if 0xD800 <= i <= 0xDFFF:
            continue
        if pred(chr(i)):
            if start is None:
                start = prev = i
            elif i == prev + 1:
                prev = i
            else:
                out.append((start, prev))
                start = prev = i
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out


def emit(name: str, ranges: list[tuple[int, int]]) -> list[str]:
    lines = [
        f"/// Inclusive [first, last] code-point ranges where single-character `str.{name}()` holds.",
        f"pub const {name.upper()}_RANGES: &[(u32, u32)] = &[",
    ]
    lines.extend(f"    (0x{a:04X}, 0x{b:04X})," for a, b in ranges)
    lines.append("];")
    return lines


LOOKUP = """
/// Binary membership test over an inclusive-range table.
fn in_ranges(cp: u32, ranges: &[(u32, u32)]) -> bool {
    ranges
        .binary_search_by(|&(lo, hi)| {
            if cp < lo {
                std::cmp::Ordering::Greater
            } else if cp > hi {
                std::cmp::Ordering::Less
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// Single-character `str.isupper()`.
pub fn is_upper(c: char) -> bool {
    in_ranges(c as u32, UPPER_RANGES)
}

/// Single-character `str.islower()`.
pub fn is_lower(c: char) -> bool {
    in_ranges(c as u32, LOWER_RANGES)
}
"""


def main() -> None:
    upper = verdict_ranges(lambda c: c.isupper())
    lower = verdict_ranges(lambda c: c.islower())
    lines = [HEADER]
    lines.extend(emit("upper", upper))
    lines.append("")
    lines.extend(emit("lower", lower))
    lines.append(LOOKUP)
    Path("src/case_tables.rs").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(upper)} upper + {len(lower)} lower ranges")


if __name__ == "__main__":
    main()
