#!/usr/bin/env python3
"""Regenerate `src/html_entities.rs` from the running interpreter's tables.

Run under the repo uv Python (CPython 3.13): a newer interpreter's entity
data silently changes the tables.

`modules/html.py` decodes entities through BeautifulSoup's `html.parser`
builder, which consults two mappings:

* text: `EntitySubstitution.HTML_ENTITY_TO_CHARACTER` by bare name (the
  parser strips the semicolon first, so `&not;` and `&notit;` look up
  `not`/`notit` — the latter missing, which is why unknown references
  lose their semicolon);
* attributes: `html.entities.html5` by exact key (`ref[1:]`, semicolon or
  `=` included), which is why unknown references keep theirs there.

Both are baked: ~2,100 entries each, binary-searched at runtime.

Regenerate only when the MSRV Python's entity data changes, then re-run
the entity matrix in the Phase 3 differential. Any delta means the HTML
normalizer needs re-verification, not silent acceptance.
"""

from __future__ import annotations

import html.entities
from pathlib import Path

HEADER = """\
//! HTML entity tables, baked from CPython + BeautifulSoup.
//!
//! Generated by `etc/gen_html_entities.py` — do not edit by hand.
"""


def rust_str(value: str) -> str:
    """A Rust double-quoted string literal for `value`."""
    out = []
    for char in value:
        code = ord(char)
        if char == '"':
            out.append('\\"')
        elif char == "\\":
            out.append("\\\\")
        elif char == "\n":
            out.append("\\n")
        elif char == "\r":
            out.append("\\r")
        elif char == "\t":
            out.append("\\t")
        elif 0x20 <= code <= 0x7E:
            out.append(char)
        elif code <= 0xFFFF:
            out.append(f"\\u{{{code:04X}}}")
        else:
            out.append(f"\\u{{{code:X}}}")
    return '"' + "".join(out) + '"'


def emit_str_table(name: str, pairs: list[tuple[str, str]]) -> list[str]:
    lines = [
        f"/// `{name}`: sorted `(name, replacement)` entries.",
        f"pub const {name}: &[(&str, &str)] = &[",
    ]
    lines.extend(f"    ({rust_str(a)}, {rust_str(b)})," for a, b in pairs)
    lines.append("];")
    return lines


def main() -> None:
    from bs4.dammit import EntitySubstitution

    bare = sorted(EntitySubstitution.HTML_ENTITY_TO_CHARACTER.items())
    html5 = sorted(html.entities.html5.items())
    lines = [HEADER]
    lines.extend(emit_str_table("HTML_ENTITIES", bare))
    lines.append("")
    lines.extend(emit_str_table("HTML5_ENTITIES", html5))
    lines.append("")
    lines.append("/// Binary lookup over a sorted entity table.")
    lines.append("fn lookup(table: &'static [(&'static str, &'static str)], name: &str) -> Option<&'static str> {")
    lines.append("    table")
    lines.append("        .binary_search_by(|(key, _)| key.cmp(&name))")
    lines.append("        .ok()")
    lines.append("        .map(|index| table[index].1)")
    lines.append("}")
    lines.append("")
    lines.append("/// A bare-name lookup, exactly what the builder consults for text.")
    lines.append("pub fn html_entity(name: &str) -> Option<&'static str> {")
    lines.append("    lookup(HTML_ENTITIES, name)")
    lines.append("}")
    lines.append("")
    lines.append("/// An exact-key lookup (`html.entities.html5`), what attributes use.")
    lines.append("pub fn html5_entity(key: &str) -> Option<&'static str> {")
    lines.append("    lookup(HTML5_ENTITIES, key)")
    lines.append("}")
    Path("src/html_entities.rs").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {len(bare)} bare + {len(html5)} html5 entries")


if __name__ == "__main__":
    main()
